import type { Metadata } from "next";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { Montserrat } from 'next/font/google';

const bangers = Montserrat({
  weight: '400',
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${bangers.className} min-h-[100vh] flex justify-center`}>
        <div className="border-2 max-w-[64rem] w-full flex flex-col gap-4">
          <Navbar />
          {children}
        </div>
      </body>
    </html>
  );
}
